#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum Action {
    MoveDown,
    MoveUp,
    MoveTaskDown,
    MoveTaskUp,
    StartAdd,
    StartEdit,
    ToggleComplete,
    Delete,
    RestoreLatest,
    OpenHelp,
    CloseHelp,
    InsertChar(char),
    MoveCursorLeft,
    MoveCursorRight,
    MoveCursorStart,
    MoveCursorEnd,
    DeleteBeforeCursor,
    DeleteAtCursor,
    CommitEdit,
    CancelEdit,
    Quit,
}
